# Generated by Django 3.0.1 on 2022-08-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_frequency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binoperation',
            name='bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bin', related_query_name='bin', to='collection_frequency.Bin'),
        ),
        migrations.AlterField(
            model_name='binoperation',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation', related_query_name='operation', to='collection_frequency.Operation'),
        ),
    ]
