# Generated by Django 3.0.1 on 2022-08-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationrecord',
            options={'verbose_name': 'Navigation Record', 'verbose_name_plural': 'Navigation Records'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
    ]
