# Generated by Django 3.0.1 on 2022-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation_record', '0003_auto_20220802_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrecord',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
